### PR TITLE
3 pip packaging from main

### PR DESCRIPTION
**Pull request by andrewgin**
tested by uploading to test.pypi:
https://test.pypi.org/project/stixorm/0.1.0/
https://test.pypi.org/project/stixorm/0.1.3/

installed with:
`pip install --index-url https://test.pypi.org/simple/ --no-deps stixorm`

and tested 
```
from stixorm.utils import check_func
check_func.get_local_relns()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_local_relns() missing 1 required positional argument: 'dep_insert'
```

### CODE REVIEW

**Comment by priamai** [comment]
What does this do?

`check_func.get_local_relns()`

**Comment by priamai** [comment]
Hello @andrewgin we have to find a way to reference the schema files directly from the pip package.
Basically how can we autofill the schema path to point into the installed pip folder?

https://github.com/os-threat/Stix-ORM/blob/main/os-intel/run_pip.ipynb

**Comment by andrewgin** [comment]
> What does this do?
> 
> `check_func.get_local_relns()`

Don't know what it does, I was just using it as an example to test that I could import the package and run a function from it

**Comment by andrewgin** [comment]
> Hello @andrewgin we have to find a way to reference the schema files directly from the pip package. Basically how can we autofill the schema path to point into the installed pip folder?
> 
> https://github.com/os-threat/Stix-ORM/blob/main/os-intel/run_pip.ipynb

ok I'll need to investigate this, I wasn't sure what functionality to test in the package, but I will test with this.

**Comment by priamai** [comment]
> > What does this do?
> > `check_func.get_local_relns()`
> 
> Don't know what it does, I was just using it as an example to test that I could import the package and run a function from it

Yeah use my code to make sure you can at least open a database connection. We have to solve the reference to the schema paths, it should be automatically set to the corresponding folder in the package. Once that is fixed I can then progress into more deeper testing.

**Comment by andrewgin** [comment]
> > > What does this do?
> > > `check_func.get_local_relns()`
> > 
> > 
> > Don't know what it does, I was just using it as an example to test that I could import the package and run a function from it
> 
> Yeah use my code to make sure you can at least open a database connection. We have to solve the reference to the schema paths, it should be automatically set to the corresponding folder in the package. Once that is fixed I can then progress into more deeper testing.

I have tested your code and it can clear the db. This isn't 'fixed'; I will need to read the code to see why we need to write within the package

**Comment by dfjosullivan** [comment]
There were changes need to get the pip package to work because of the referencing to schemas. I am merging this as the module names have changed. Any further changes can just be raised as additional PRs

**Pull request merged**
